"""Generator for `results/sensitivity.md` (`EVAL.md §6A` / `§7.1 item C`).

Structural-only regeneration: renders the sweep grid's cell membership
(cell_id, parameter, handle, direction, low-information flag) directly
from `enumerate_cells()` + `required_wins()` (`src/rrx/spec/registry.py`,
locked) — the same functions `tests/test_model_params_swept.py` (locked)
already pins to 26 cells / 21 required wins. This module does NOT run,
and has no ability to run, the actual `dev`-split sensitivity sweep: no
result column (`clamped` / `invoice CI` / `rescue CI` / `win`) is computed
here — every one is rendered `PENDING` until a real sweep is executed and
its output is wired through this same renderer. No cell is added, removed,
or reordered relative to `enumerate_cells()`'s own output.

Historical note this module exists to fix: the previous static
`results/sensitivity.md` (and `configs/model_params.yaml`'s own header)
claimed to be "Generated by `make docs`", but no such Makefile target and
no generator of any kind existed anywhere in this repository before this
module — confirmed by exhaustive search (no reference to "sensitivity.md"
or "make docs" in any `.py` file or the `Makefile`). That file's 22-row
structure predated `eval-spec-v1.1`'s cell-count correction (22 -> 26,
see `tests/test_model_params_swept.py`'s own module docstring) and was
never updated to match. This module makes the "Generated by `make docs`"
claim true, wired via the `Makefile`'s new `docs` target, rather than
removing the claim.
"""

from __future__ import annotations

from pathlib import Path

from rrx.spec.registry import Cell, Registry, enumerate_cells, load_registry, required_wins

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT_PATH = REPO_ROOT / "results" / "sensitivity.md"

PENDING = "PENDING"


def _row(cell: Cell) -> str:
    low_info = "yes" if cell.low_information else ""
    return (
        f"| `{cell.cell_id}` | {cell.parameter} | {cell.handle} | {cell.direction} "
        f"| {PENDING} | {PENDING} | {PENDING} | {PENDING} | {low_info} |"
    )


def render_sensitivity_md(reg: Registry | None = None) -> str:
    """Renders `results/sensitivity.md`'s full content from the registry.

    Cell membership, order, and count come entirely from `enumerate_cells`
    — nothing here adds, drops, or reorders a cell relative to that
    function's own output. The pass mark comes from `required_wins`, the
    same function `test_required_wins_is_ceil_of_eighty_percent` already
    pins to 21 for 26 cells. No experiment result is fabricated: every
    outcome column is the literal string "PENDING" until a real sweep run
    supplies rows of its own.
    """
    reg = reg or load_registry()
    cells = enumerate_cells(reg)
    n = len(cells)
    wins_required = required_wins(n, reg)

    lines = [
        "# results/sensitivity.md",
        "",
        "Generated by `make docs`. Do not hand-edit. Losing cells are published, never dropped.",
        "",
        "- Split: `dev` (locked decision 1)",
        "- Method: one_at_a_time, magnitude 30%",
        "- Win: both Regime-B primary metrics beat A2, paired 95% CI excludes zero",
        f"- Pass mark: {wins_required} / {n} cells (ceil of 80%)",
        "",
        "| cell_id | parameter | handle | dir | clamped | invoice CI | "
        "rescue CI | win | low-info |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    lines.extend(_row(c) for c in cells)
    lines.append("")
    lines.append(f"**Cells won: {PENDING} / {n}. Pass mark {wins_required}.**")
    lines.append("")
    lines.append(
        "Low-information cells (wait/escalate buckets, <=5% mass) are counted in the\n"
        "denominator per locked decision 13 and flagged, not removed."
    )
    return "\n".join(lines) + "\n"


def main(output_path: Path | None = None) -> Path:
    """Writes the rendered content to `results/sensitivity.md` (or
    `output_path`, for tests). Always overwrites — this file is
    machine-generated and never hand-edited (per its own header)."""
    output_path = output_path or DEFAULT_OUTPUT_PATH
    output_path.write_text(render_sensitivity_md(), encoding="utf-8")
    return output_path


if __name__ == "__main__":
    main()
